### ISSUE TITLE
Sample request - Push notifications

### ISSUE THREAD

**Issue by mba645** [DKE-Data/agrirouter-api-dotnet-standard#61]
Hi, 

I have some trouble with implementing the push notifications for telemetry and receiving Taskdatas.
Could you please provide a sample on how to activate the functionnality and how to receive data through it?
If there is something special to set up in order to send data from a device like a CCI, would it be possible to provide a procedure as well?

Thanks a lot

**Comment by saschadoemer** [comment]
@mba645 I am currently working on this, but I only get a "Server unavailable" from the AR while connecting with the MQTT client. Could you perhaps share a snippet that will show how you connected to the AR?

**Comment by saschadoemer** [comment]
@mba645 Please see the following file for a working example with HTTP communication. The behavior is the same for MQTT. All steps are documented within the test case.

[Implementation example for HTTP communication](https://github.com/DKE-Data/agrirouter-api-dotnet-standard/blob/develop/agrirouter-api-dotnet-standard-test/Integration/CleanYourFeedWithConfirmingMessagesIntegrationTest.cs)

**Comment by mba645** [comment]
@saschadoemer How can Push Notifications even work if Push Notification properties on both Sender and Receiver are set to disabled ?
If it is still of interest, I will send you a short implementation of how I implemented the MQTT client shortly.

**Comment by saschadoemer** [comment]
@mba645 Hmmm, looks like I mentioned the wrong reference. Since I was using already existing endpoints and routes I was not aware, that the current implementation has a major issue - the capabilities message is not enabling push notifications. I was writing some test cases to show the example and detected that issue during debugging. Since this is a major impact, I will open a new issue for it and then provide an implementation example within the tests. 

Regarding the short implementation how to implement the MQTT client --> I would be thankful to see that. My current implementation was working, but currently is not. 

Please stay tuned until upcoming week. I am working on that fix.

**Comment by saschadoemer** [comment]
@mba645 Please check #67 for an example that is not yet merged into the main branch.

**Comment by mba645** [comment]
Please find attached a short Winform implementation of the MQTT client for Agrirouter.
You will have to add your own OnboardResponse, ApplicationId and CertificationVersionId to make it work.
This works with the Nuget packages stored on your GitHub, you will have to add your token in the nuget.config file to get the packages.

[Agrirouter.Winform.zip](https://github.com/DKE-Data/agrirouter-api-dotnet-standard/files/5829298/Agrirouter.Winform.zip)

**Comment by mba645** [comment]
Sorry for the late response, I took a look on the PR you mentionned. 
If I understand it correctly, with http protocol and PushNotification enabled, I would still have to fetch the messages in the outbox through a request, am I right ? That's precisely what I try to avoid and why I am working with the MQTT implementation.
However, I don't really know how to apply this. Do you have additionnal information for MQTT ?

**Comment by saschadoemer** [comment]
@mba645 No problem, the PR is already merged - therefore no problem. Using MQTT you would not need to fetch the messages with a query. Since the outbox of the HTTP endpoints can only be polled there would be a GET request. Using MQTT you would have the messages pushed in your topic without any further query. You should still use a frequent query to fetch and confirm any missed messages.

**Comment by mba645** [comment]
When do you think the next release date will be? Since I am working with the generated NuGet packages, I won't be able to test this until then.

**Comment by saschadoemer** [comment]
I am able to release this asap.
